contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #differentialabundance channel"
    url: https://nfcore.slack.com/channels/differentialabundance
    about: Discussion about the nf-core/differentialabundance pipeline
